url: "https://docteur.fleurette.me" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Docteur Denis Fleurette" # the name of your site, e.g. ACME Corp.
description: "Le cabinet du docteur Denis Fleurette est définitivement fermé depuis le 31/03/2020. Le docteur Fleurette est à présent à la retraite. Merci de votre compréhention."